version: "3.8"
services:
  Backend:
    build: ./backend
    container_name: api
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: web
    ports:
      - "8081:80"
    depends_on:
      - Backend
